// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PMS.NET_7.Shared.Models;

[Table("ApplicationTypesTable")]
public partial class ApplicationTypesTable
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ApplicationType { get; set; }

    [InverseProperty("ApplicationType")]
    public virtual ICollection<ProjectsTable> ProjectsTables { get; } = new List<ProjectsTable>();
}