// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PMS.NET_7.Shared.Models;

[Table("ProjectsTable")]
public partial class ProjectsTable
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProjectName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProjectCode { get; set; }

    public int? ProjectTypeID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TargetCompletionDate { get; set; }

    public int? EstimatedCost { get; set; }

    [Unicode(false)]
    public string ProjectImage { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    public int? ProjectProgressID { get; set; }

    public int? GameTypeID { get; set; }

    public int? ApplicationTypeID { get; set; }

    [ForeignKey("ApplicationTypeID")]
    [InverseProperty("ProjectsTables")]
    public virtual ApplicationTypesTable ApplicationType { get; set; }

    [ForeignKey("GameTypeID")]
    [InverseProperty("ProjectsTables")]
    public virtual GameTypesTable GameType { get; set; }

    [ForeignKey("ProjectProgressID")]
    [InverseProperty("ProjectsTables")]
    public virtual ProjectProgress ProjectProgress { get; set; }

    [ForeignKey("ProjectTypeID")]
    [InverseProperty("ProjectsTables")]
    public virtual ProjectTypesTable ProjectType { get; set; }
}